[project]
name = "e-commerce-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "django>=6.0",
    "pillow>=12.0.0",
    "psycopg2-binary>=2.9.11",
    "pycountry>=24.6.1",
]
